backend:
  image:
    repository: backend
    tag: "1.0.0"
  replicaCount: 1
  nodeSelector:
  name: Stakater
  service:
    type: NodePort
    port: 5001

frontend:
  image:
    repository: frontend
    tag: "1.0.0"
  replicaCount: 1
  nodeSelector:
  service:
    type: NodePort
    port: 3000

common:
  imagePullSecret: docker-secret
  imagePullPolicy: IfNotPresent
