---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "backend.fullname" . }}
  labels:
    app: {{ template "backend.fullname" . }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "backend.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "backend.fullname" . }}
    spec:
      containers:
        - name: {{ template "backend.fullname" . }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.common.imagePullPolicy }}
          env:
          - name: NAME
            value: {{ .Values.backend.name }}
          ports:
            - name: 'flask-port'
              containerPort: 5001
              protocol: TCP