---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "backend.fullname" . }}
  labels:
    app: {{ template "backend.fullname" . }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 5001
      protocol: TCP
  selector:
    app: {{ template "backend.fullname" . }}