apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stakater-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
spec:
  defaultBackend:
    service:
      name: {{ template "frontend.fullname" . }}
      port:
        number: 3000
  rules:
    - host: stakater.info
      http:
        paths:
          # - path: /
          #   pathType: Prefix
          #   backend:
          #     service: 
          #       name: {{ template "frontend.fullname" . }}
          #       port:
          #         number: 3000
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ template "backend.fullname" . }}
                port:
                  number: 5001