---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "frontend.fullname" . }}
  labels:
    app: {{ template "frontend.fullname" . }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "frontend.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "frontend.fullname" . }}
    spec:
      containers:
        - name: {{ template "frontend.fullname" . }}
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.common.imagePullPolicy }}
          ports:
            - name: 'react'
              containerPort: 3000
              protocol: TCP