---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "frontend.fullname" . }}
  labels:
    app: {{ template "frontend.fullname" . }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 3000
      protocol: TCP
  selector:
    app: {{ template "frontend.fullname" . }}